import Head from "next/head";
import { Inter } from "next/font/google";
import styles from "@/styles/HomeSection.module.css";
import Header from "@/components/Header";
import HomeSection from "@/components/HomeSection";
import AboutUs from "@/components/AboutUs";
import Services from "@/components/Services";
import Resume from "@/components/Resume";
import Portfolio from "@/components/Portfolio";
import ContactUs from "@/components/ContactUs";
import Footer from "@/components/Footer";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Taher</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />

      <main>
        <HomeSection />
        <AboutUs />
        {/*<Services />*/}
        <Resume />
        <Portfolio />
        {/*<ContactUs />*/}
      </main>

      <Footer />
    </>
  );
}
